/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AddInput: typeof import('./src/components/AddInput.vue')['default']
    AddKnowledgeBtn: typeof import('./src/components/AddKnowledgeBtn.vue')['default']
    AddKnowledgeDialog: typeof import('./src/components/AddKnowledgeDialog.vue')['default']
    AddSiderCard: typeof import('./src/components/AddSiderCard.vue')['default']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ATable: typeof import('ant-design-vue/es')['Table']
    Chat: typeof import('./src/components/Chat.vue')['default']
    DefaultModal: typeof import('./src/components/DefaultModal.vue')['default']
    Defaultpage: typeof import('./src/components/Defaultpage.vue')['default']
    DeleteModal: typeof import('./src/components/DeleteModal.vue')['default']
    FileUploadDialog: typeof import('./src/components/FileUploadDialog.vue')['default']
    Head: typeof import('./src/components/Head.vue')['default']
    ManageCard: typeof import('./src/components/ManageCard.vue')['default']
    NewAddKnowledgeDialog: typeof import('./src/components/NewAddKnowledgeDialog.vue')['default']
    OptionList: typeof import('./src/components/OptionList.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchKnowledgeInput: typeof import('./src/components/SearchKnowledgeInput.vue')['default']
    Sider: typeof import('./src/components/Sider.vue')['default']
    SiderCard: typeof import('./src/components/SiderCard.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    UploadDom: typeof import('./src/components/UploadDom.vue')['default']
    UploadInput: typeof import('./src/components/UploadInput.vue')['default']
    UploadList: typeof import('./src/components/UploadList.vue')['default']
    UrlUploadDialog: typeof import('./src/components/UrlUploadDialog.vue')['default']
  }
}
