FROM localhost/xixihahaliu01/qanything-mac:v1.5.0

# 安装必要的工具
RUN apt-get update && apt-get install -y --no-install-recommends \
    vim \
    htop \
    && rm -rf /var/lib/apt/lists/*

# 卸载 CPU 版本的 onnxruntime 并安装兼容的 GPU 版本
RUN pip install --no-cache-dir docx2txt ipython

# 清理
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
